### ISSUE TITLE
Controller model

### ISSUE THREAD

**Issue by Zomby2D** [NOLOVR/NOLO-Android-SDK#1]
Would it be possible to have a skinned controller model, similar to [what Google does](https://github.com/googlevr/gvr-android-sdk/tree/master/assets/controller) for their Daydream controller?

It would be nice being able to show the controllers in-game.

**Comment by Hettylool** [comment]
https://github.com/NOLOVR/NOLO-Others/tree/master/NOLO_Controller_Model
